# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'No te limites' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'

  # Pods for No te limites

  target 'No te limitesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'No te limitesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
